### ISSUE TITLE
Generating embeddings for Python and Java

### ISSUE THREAD

**Issue by Avv22** [tech-srl/code2seq#104]
Hello,

Thanks again for your work. 

Can you please explain how to use the model to generate embeddings for a source file in Python and also for Java? Do we have to train your model on Java dataset and Python dataset in order to use the model to generate embeddings of source code? Also is it possible to have embeddings in a fixed size of let us say 100 represented as numerical data for each file?

**Comment by urialon** [comment]
Hi Avra,
Thank you for your interest in this work! Sorry again for the delayed response.

Yes, in order to use code2vec for python, you will have to train the model on a python dataset.
Have you seen this section in the README? [https://github.com/tech-srl/code2vec#extending-to-other-languages](https://github.com/tech-srl/code2vec#extending-to-other-languages)

Uri

**Comment by Avra2** [comment]
> Hi Avra, Thank you for your interest in this work! Sorry again for the delayed response.
> 
> Yes, in order to use code2vec for python, you will have to train the model on a python dataset. Have you seen this section in the README? https://github.com/tech-srl/code2vec#extending-to-other-languages
> 
> Uri

Hello Dr. Uri,

I got output from astminer after astminer team helped me, so what to do next please? How to train code2vec model? For 5 files only from astminer, I got the following files:

![image](https://user-images.githubusercontent.com/45768058/139622586-6be264d5-5f8f-4464-bac1-ef44a870688d.png)

Each of these files has lots of rows (over 100 rows) for only 5 python files, so I am just confused to what I should do next with these outputs from astminer and how I can train code2vec to produce only one embedding for each python file?

**Comment by Avra2** [comment]
@urialon. `astminer` tool produces over 40 rows for 5 python files in `python.c2v` file as output. So for 20k files for example that would be hundered of thousands of rows. Is this okay to train code2vec with please? Then, once I finish training, can I use the trained model to produce one embedding row for each file please?

**Comment by Avv22** [comment]
@urialon. astminer team helped me producing training, testing and validation `python.c2v` data. So, how we should proceed next please to train code2vec model? Then once we train the model, can we feed the same data to produce embeddings as we have 20k python files that we split into train, test and validate before feeding them to astminer tool. Once we train code2vec, we would like to feed the same python code to produce embeddings, so what do you think please?

**Comment by urialon** [comment]
I am not sure how your `python.c2v` look like, but try to continue running the `preprocess.sh` script starting from this line: [https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L54](https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L54) (and adapt all paths according to your files).

**Comment by Avv22** [comment]
@urialon. 

Thank you. So I will train your model on 150k python dataset. How to please save the model to use it later on another python dataset to generate embeddings? Does the `preprocessor.sh` does it automatically and save the model please?

We would like too once we train the model on 150k python dataset you specified to use to generate later on one embedding vector for each python file we have in our own dataset, can we do that please? We don't want to generate method name but one embedding that is representative of a file. We would like to do the same for our 20k python files.

**Comment by urialon** [comment]
Hi @Avra2 ,

`preprocess.sh` just preprocesses the data, it does not even train the model.
However, `train.sh` trains and saves the checkpoints. See:
[https://github.com/tech-srl/code2vec#training-a-model-from-scratch](https://github.com/tech-srl/code2vec#training-a-model-from-scratch)
