### ISSUE TITLE
Timeout from EXTRACTION_API for large Input.Java files

### ISSUE THREAD

**Issue by vbellur** [tech-srl/code2seq#11]
Hi, 

While running interactive_predict, I get a timeout error (20s) from the extraction API if Input.Java contains multiple functions and happens to be reasonably big. Would you recommend using the JavaExtractor available in code2seq repo for such cases? Also, could you please share details on the json format used by EXTRACTION_API for encoding the output?

Thank you and very much appreciate the work that you are doing!

**Comment by urialon** [comment]
Yes.
The extraction API is meant to serve the website demo (code2seq.org) and small lightweight examples.
For more massive use, please use the Java Extractor to preprocess a large batch of examples, and then use the "--test" mode to feed them to the model.

Let me know if you have any more questions.

Best,
Uri
