### ISSUE TITLE
Extract Path Contexts Only

### ISSUE THREAD

**Issue by Avv22** [tech-srl/code2seq#110]
Hello,

Given that both your models code2seq and code2vec are initially made to predict **method name** from source code body represented as **path context**, can you please give give how to extract **path context** as we are just looking for source code representation of the source code.

Thank you.

**Comment by urialon** [comment]
Hi @Avra2 ,

What exactly do you mean by "extract path context"?
Do you want the paths? (it's in the raw dataset)
These paths' representations? (do you really want ~200 vectors for every
example?)
The aggregation of these 200 vectors? (this is the "code vector")

Uri

**Comment by lyriccoder** [comment]
Seems @Avra2 wants to get `paths`. 
Try to compile Java application inside the project or just find the compiled jar file.

You can run it  with `java -cp JavaExtractor/JPredict/target/JavaExtractor-0.0.2-SNAPSHOT.jar JavaExtractor.App --max_path_length=8 --max_path_width=2 --file filename`, where `filename` is a file with a java function.


Suppose, you have the code:
```
public boolean f(Set<String> set, String value) 
{  
   for (String entry : set) 
   {  
       if (entry.equalsIgnoreCase(value)) 
       {  
           return true ;   
        }  
   }  
   return false;  
}
```

So, the code will be translated into the following list of paths:
```
set GenericClass1|Prm|Mth|Bk|Foreach|VDE|VD|VDID0 entry
METHOD_NAME Nm1|Mth|Prm|GenericClass1 set
set GenericClass1|Prm|Mth|Bk|Foreach|VDE|Cls0 string
set VDID0|Prm|GenericClass|Cls0 string
string Cls0|GenericClass|Prm|Mth|Bk|Foreach|VDE|VD|VDID0 entry
string Cls0|GenericClass|Prm|Mth|Prm|Cls1 string
set GenericClass|Cls0 string
set GenericClass1|Prm|Mth|Bk|Foreach|Nm1 set
string Cls0|GenericClass|Prm|Mth|Bk|Foreach|Nm1 set
boolean Prim0|Mth|Prm|GenericClass|Cls0 string
METHOD_NAME Nm1|Mth|Prm|GenericClass|Cls0 string
set GenericClass1|Prm|Mth|Prm|VDID0 value
set GenericClass1|Prm|Mth|Bk|Ret|BoolEx0 false
set GenericClass1|Prm|Mth|Bk|Foreach|Bk|If|Cal0|Nm3 equals|ignore|case
boolean Prim0|Mth|Prm|GenericClass1 set
string Cls0|GenericClass|Prm|Mth|Prm|VDID0 value
set GenericClass1|Prm|Mth|Bk|Foreach|Bk|If|Cal0|Nm2 value
set GenericClass1|Prm|Mth|Bk|Foreach|Bk|If|Cal0|Nm0 entry
set VDID0|Prm|GenericClass1 set
string Cls0|GenericClass|Prm|Mth|Bk|Ret|BoolEx0 false
string Cls0|GenericClass|Prm|Mth|Bk|Foreach|VDE|Cls0 string
set GenericClass1|Prm|Mth|Prm|Cls1 string
```

Did u want those lists of paths (you called it "path context")?

**Comment by Avv22** [comment]
@lyriccoder @urialon. Thanks for response. By **path context**, I don't refer to paths extracted by parser but **aggregated path** learned by your model by the help of attention mechanism as this should be "the most that contributes to method name" please? So can we use this "**vector that the most that contributes to method name**" as representation embedding for the whole file or this is **just** useful for your task, which is method name prediction? If this vector can be used for various tasks, then can you please show how to extract it from your network during training? 

Thanks.

**Comment by urialon** [comment]
Did you try this?
https://github.com/tech-srl/code2seq#step-4-manual-examination-of-a-trained-model

**Comment by Avv22** [comment]
@urialon. Thank you.
