### ISSUE TITLE
Visualize Python AST

### ISSUE THREAD

**Issue by Avv22** [tech-srl/code2seq#113]
Hello,

I tried to use your  website to visualize AST of the code. Your oniline tool supports Java, C# but it does not support Python. Can you please refer a good AST visualizer for Python code? I am not sure if your tool is able to visualize AST for Python, but it gave me error.

Thanks.

**Comment by urialon** [comment]
Sorry,
I don’t know, and our website  supports only Java.

But I see that Google gives some relevant results when I search for "python
ast visualizer".

Good luck!
Uri

**Comment by Avv22** [comment]
@urialon. Thank you.
