### ISSUE TITLE
Extract java files

### ISSUE THREAD

**Issue by Auzel** [tech-srl/code2seq#114]
I am trying to reproduce the experiment for this paper, and will like to obtain the java training and test examples used. They seem to be packaged in a .c2s file. So, how can I extract these java files from .c2s packaged file?

**Comment by urialon** [comment]
Hi @Auzel , thank you for your interest in our work!
the `.c2s` files are _preprocessed_ already. The raw `*.java` files are also available, see [https://github.com/tech-srl/code2seq#datasets](https://github.com/tech-srl/code2seq#datasets)

Best,
Uri

**Comment by Auzel** [comment]
Thanks
