### ISSUE TITLE
Trainable Model? (Similar to Code2Vec)

### ISSUE THREAD

**Issue by MarcelLuz** [tech-srl/code2seq#12]
Hey, 

I am a Master student at the HTWG Konstanz University of Applied Sciences in Computer Science.

Currently, I am working on my master thesis, where I am investigating various machine learning methods that deal with the naming of variables and methods.

My idea is to train a model even further, for example to adapt it for a certain domain, which uses other technical terms for the method names.

I saw that you provided a trainable model for code2vec. 
Would it be possible for you to provide something like this for code2seq?

Thanks,
Marcel

**Comment by urialon** [comment]
Hi Marcel, 
Sorry, I don't have the model which includes both testing and training graphs.
But I think that the existing code2seq model **can** be further trained, did you check?

**Comment by MarcelLuz** [comment]
Hello, Uri,
Thanks for your quick reply.

I assumed that the model is in the "released" state and can't be further trained.

I have not tested it yet. But I'll give it a try.

Thanks
