### ISSUE TITLE
Extraction API giving 403 Forbidden

### ISSUE THREAD

**Issue by claudiosv** [tech-srl/code2seq#13]
Hi, I loaded the pre-trained model and trying the predict in interactive mode on the sample function given in Input.java. However, the Extraction API (https://ff655m4ut8.execute-api.us-east-1.amazonaws.com/production/extractmethods) used in the code is giving a 403 Forbidden error, like issue #7.

I'd be happy to modify the JavaExtractor to output the required data as in the JSON normally returned by the API. It would be easier to do this if some examples of the response JSON were available.

Thank you!

**Comment by urialon** [comment]
Hi Claudio, thanks for letting me know. I'll take care of it and let you know once it is fixed.

**Comment by claudiosv** [comment]
Hi Uri, thank you for your super fast response!

**Comment by urialon** [comment]
Hi @claudiosv ,
Can you please change the extraction API here: [https://github.com/tech-srl/code2seq/blob/master/interactive_predict.py#L7](https://github.com/tech-srl/code2seq/blob/master/interactive_predict.py#L7)
to this:

`https://po3g2dx2qa.execute-api.us-east-1.amazonaws.com/production/extractmethods`

it works for me.
I will change this in the code and in the websites.
Let me know how it goes

**Comment by claudiosv** [comment]
Hi @urialon ,

It works! You're a legend! Thank you so much.
