### ISSUE TITLE
issue about data preprocess

### ISSUE THREAD

**Issue by shangqing-liu** [tech-srl/code2seq#14]
Hi,
May I ask when I read your codes about reader.py, I doubted the function process_dataset, the sample of the maximum contexts:

safe_limit = tf.cast(tf.maximum(num_contexts_per_example, self.config.MAX_CONTEXTS), tf.int32)
rand_indices = tf.random_shuffle(tf.range(safe_limit))[:self.config.MAX_CONTEXTS]
contexts = tf.gather(all_contexts, rand_indices)  # (max_contexts,)

seems will be array out of bounds.

**Comment by urialon** [comment]
Hi,
There is no array out of bound, because there is padding. Even when there are less than max_contexts, there are paddings instead.

Best,
Uri

**Comment by shangqing-liu** [comment]
got it, thanks very much @urialon
