### ISSUE TITLE
model performance on long word sequences

### ISSUE THREAD

**Issue by shangqing-liu** [tech-srl/code2seq#15]
Hi, 
 I have tested your methods on translating long sequences based ast paths, but I found the performance is much lower than expected, may I ask you some suggestions about this problem or do you have tested on translating long sequences.

**Comment by urialon** [comment]
Hi,
Please provide more details:

1. Which data did you use
2. Which model did you use
3. Did you trained the model yourself? If so, did you change any parameters from the default values?
4. What is the problem?

**Comment by shangqing-liu** [comment]
Hi, I used my own data on C projects and trained the model by myself. The best f1 seems to reach only 23% and the blue score is much slower.

**Comment by shangqing-liu** [comment]
Sir, may I ask you a question what is the meaning of --max_path_length 8 --max_path_width 2 in your preprocess.sh
thanks very much

**Comment by urialon** [comment]
You can try increasing the number of decoder layers (`config.NUM_DECODER_LAYERS`) to 2 and their size ( `config.DECODER_SIZE` ) to 512 [in the config](https://github.com/tech-srl/code2seq/blob/master/config.py) file. 
Adding more data always helps...

Regarding path length and width - 
Please see the paragraph "Path length and width" in Section 4.2 [in the PLDI paper](http://urialon.cswp.cs.technion.ac.il/wp-content/uploads/sites/83/2018/07/pldi18_paper.pdf)

**Comment by shangqing-liu** [comment]
sir, have you tested your method on large functions, the experimental results seem to be worse than small functions.

**Comment by urialon** [comment]
Yes, please see Section 4.1, paragraph "Sensitivity to input length," in [the code2seq paper](https://openreview.net/pdf?id=H1gKYo09tX).
