### ISSUE TITLE
Timeout Error while Preprocessing Java-Small

### ISSUE THREAD

**Issue by aendel** [tech-srl/code2seq#21]
Hello researcher from tech-srl,
I'm a soon to graduate student, I'm trying to understand how to preprocess data in order to try later code2seq with a new dataset which I would like to build on my own.
I would like to ask you few question:
How could I prevent all the ram of my pc from being saturate during the preprocessing?
I have notified that while the extraction of the training set ( which is actually only a sub folder from the whole java small training folder right now in my case) the memory is totally used and after that the follow error appear. 
My pc specs are :
```
CPU: AMD® Ryzen 5 3600 6-core processor × 12
GPU: NVIDIA GeForce GTX 1660/PCIe/SSE2
RAM: 16 GB
OS: Ubuntu 18.04
```
```
Extracting paths from validation set...
Finished extracting paths from validation set
Extracting paths from test set...
Finished extracting paths from test set
Extracting paths from training set...
dir: /home/francesco/Scrivania/Thesis/code2seq/data/noProcessed/java-small/training/elasticsearch was not completed in time
Finished extracting paths from training set
Creating histograms from the training data
subtoken vocab size:  0
node vocab size:  0
target vocab size:  0
File: my_dataset.test.raw.txt
Average total contexts: 220.83893135123765
Average final (after sampling) contexts: 89.03593717130636
Total examples: 57044
Max number of contexts per word: 13272
File: my_dataset.val.raw.txt
Average total contexts: 164.20042778057373
Average final (after sampling) contexts: 70.02675725549405
Total examples: 23844
Max number of contexts per word: 47830
File: my_dataset.train.raw.txt
Traceback (most recent call last):
  File "preprocess.py", line 118, in <module>
    max_contexts=int(args.max_contexts), max_data_contexts=int(args.max_data_contexts))
  File "preprocess.py", line 55, in process_file
    print('Average total contexts: ' + str(float(sum_total) / total))
ZeroDivisionError: float division by zero
```
I would say thank you in advance for your help.

**Comment by urialon** [comment]
Hi Francesco,
Thank you for your interest in code2seq.

The ZeroDivisionError is because no examples were extracted in the previous step (for the training set), because of the timeout.
You can increase the timeout here:
[https://github.com/tech-srl/code2seq/blob/master/JavaExtractor/extract.py#L37](https://github.com/tech-srl/code2seq/blob/master/JavaExtractor/extract.py#L37)

Best,
Uri

**Comment by aendel** [comment]
Thanks Uri,

I have tried to increase the timeout, it has worked almost everytime, I have found out that it was as helpful as well to decrease the number of core from 6 to 5, which prevent the pc from freezing while processing.

**Comment by urialon** [comment]
Great! I'm glad to hear.
