### ISSUE TITLE
Could these codes support tensorflow 2.0

### ISSUE THREAD

**Issue by lishi0927** [tech-srl/code2seq#22]
I know these codes are based on graphs and sessions and the code2vec project supports tensorflow 2.0, could you give some advice how to make these codes support tensorflow 2.0?
Thank you.

**Comment by urialon** [comment]
Hi @lishi0927 ,
I don't know :)

You can try this migration tutorial:
[https://www.tensorflow.org/guide/migrate](https://www.tensorflow.org/guide/migrate)

I personally use a different virtualenv or conda environment when switching between these projects.

Best,
Uri

**Comment by lishi0927** [comment]
Thank you for your reply.
I'm a novice at tensorflow, but I'll try to this migration.
