### ISSUE TITLE
I can't preprocess java-small correctly~

### ISSUE THREAD

**Issue by BUCTwangkun** [tech-srl/code2seq#29]
when I preprocessed the dataset java-small, I encountered this problem.
（I just use one thread, because I want to map my preprocessed dataset. Using multi-threads can make the dataset mapping disorder） 

b'java.util.concurrent.ExecutionException: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 1, column 54.\n\nWas expecting one of:\n\n    "!"\n    "("\n    "+"\n    "++"\n    "-"\n    "--"\n    "boolean"\n    "byte"\n    "char"\n    "double"\n    "false"\n    "float"\n    "int"\n    "long"\n    "new"\n    "null"\n    "short"\n    "super"\n    "this"\n    "true"\n    "void"\n    "{"\n    "~"\n    <CHARACTER_LITERAL>\n    <FLOATING_POINT_LITERAL>\n    <IDENTIFIER>\n    <INTEGER_LITERAL>\n    <LONG_LITERAL>\n    <STRING_LITERAL>\n\n\n\tat java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:192)\n\tat JavaExtractor.App.lambda$extractDir$3(App.java:59)\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\n\tat JavaExtractor.App.extractDir(App.java:57)\n\tat JavaExtractor.App.main(App.java:32)\nCaused by: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 1, column 54.\n\nWas expecting one of:\n\n    "!"\n    "("\n    "+"\n    "++"\n    "-"\n    "--"\n    "boolean"\n    "byte"\n    "char"\n    "double"\n    "false"\n    "float"\n    "int"\n    "long"\n    "new"\n    "null"\n    "short"\n    "super"\n    "this"\n    "true"\n    "void"\n    "{"\n    "~"\n    <CHARACTER_LITERAL>\n    <FLOATING_POINT_LITERAL>\n    <IDENTIFIER>\n    <INTEGER_LITERAL>\n    <LONG_LITERAL>\n    <STRING_LITERAL>\n\n\n\tat com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:242)\n\tat com.github.javaparser.JavaParser.parse(JavaParser.java:210)\n\tat JavaExtractor.FeatureExtractor.parseFileWithRetries(FeatureExtractor.java:73)\n\tat JavaExtractor.FeatureExtractor.extractFeatures(FeatureExtractor.java:45)\n\tat JavaExtractor.ExtractFeaturesTask.extractSingleFile(ExtractFeaturesTask.java:64)\n\tat JavaExtractor.ExtractFeaturesTask.processFile(ExtractFeaturesTask.java:34)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:27)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:16)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\njava.util.concurrent.ExecutionException: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 7, column 2.\n\nWas expecting one of:\n\n    ";"\n    "<"\n    "@"\n    "abstract"\n    "boolean"\n    "byte"\n    "char"\n    "class"\n    "default"\n    "double"\n    "enum"\n    "final"\n    "float"\n    "int"\n    "interface"\n    "long"\n    "native"\n    "private"\n    "protected"\n    "public"\n    "short"\n    "static"\n    "strictfp"\n    "synchronized"\n    "transient"\n    "void"\n    "volatile"\n    "{"\n    "}"\n    <IDENTIFIER>\n\n\n\tat java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:192)\n\tat JavaExtractor.App.lambda$extractDir$3(App.java:59)\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\n\tat JavaExtractor.App.extractDir(App.java:57)\n\tat JavaExtractor.App.main(App.java:32)\nCaused by: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 7, column 2.\n\nWas expecting one of:\n\n    ";"\n    "<"\n    "@"\n    "abstract"\n    "boolean"\n    "byte"\n    "char"\n    "class"\n    "default"\n    "double"\n    "enum"\n    "final"\n    "float"\n    "int"\n    "interface"\n    "long"\n    "native"\n    "private"\n    "protected"\n    "public"\n    "short"\n    "static"\n    "strictfp"\n    "synchronized"\n    "transient"\n    "void"\n    "volatile"\n    "{"\n    "}"\n    <IDENTIFIER>\n\n\n\tat com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:242)\n\tat com.github.javaparser.JavaParser.parse(JavaParser.java:210)\n\tat JavaExtractor.FeatureExtractor.parseFileWithRetries(FeatureExtractor.java:73)\n\tat JavaExtractor.FeatureExtractor.extractFeatures(FeatureExtractor.java:45)\n\tat JavaExtractor.ExtractFeaturesTask.extractSingleFile(ExtractFeaturesTask.java:64)\n\tat JavaExtractor.ExtractFeaturesTask.processFile(ExtractFeaturesTask.java:34)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:27)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:16)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\njava.util.concurrent.ExecutionException: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 53, column 2.\n\nWas expecting one of:\n\n    ";"\n    "<"\n    "@"\n    "abstract"\n    "boolean"\n    "byte"\n    "char"\n    "class"\n    "default"\n    "double"\n    "enum"\n    "final"\n    "float"\n    "int"\n    "interface"\n    "long"\n    "native"\n    "private"\n    "protected"\n    "public"\n    "short"\n    "static"\n    "strictfp"\n    "synchronized"\n    "transient"\n    "void"\n    "volatile"\n    "{"\n    "}"\n    <IDENTIFIER>\n\n\n\tat java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:192)\n\tat JavaExtractor.App.lambda$extractDir$3(App.java:59)\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\n\tat JavaExtractor.App.extractDir(App.java:57)\n\tat JavaExtractor.App.main(App.java:32)\nCaused by: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 53, column 2.\n\nWas expecting one of:\n\n    ";"\n    "<"\n    "@"\n    "abstract"\n    "boolean"\n    "byte"\n    "char"\n    "class"\n    "default"\n    "double"\n    "enum"\n    "final"\n    "float"\n    "int"\n    "interface"\n    "long"\n    "native"\n    "private"\n    "protected"\n    "public"\n    "short"\n    "static"\n    "strictfp"\n    "synchronized"\n    "transient"\n    "void"\n    "volatile"\n    "{"\n    "}"\n    <IDENTIFIER>\n\n\n\tat com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:242)\n\tat com.github.javaparser.JavaParser.parse(JavaParser.java:210)\n\tat JavaExtractor.FeatureExtractor.parseFileWithRetries(FeatureExtractor.java:73)\n\tat JavaExtractor.FeatureExtractor.extractFeatures(FeatureExtractor.java:45)\n\tat JavaExtractor.ExtractFeaturesTask.extractSingleFile(ExtractFeaturesTask.java:64)\n\tat JavaExtractor.ExtractFeaturesTask.processFile(ExtractFeaturesTask.java:34)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:27)\n\tat JavaExtractor.ExtractFeaturesTask.call(ExtractFeaturesTask.java:16)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\njava.util.concurrent.ExecutionException: com.github.javaparser.ParseProblemException: Encountered unexpected token: "..." "..."\n    at line 7, column 2.\n\nWas expecting one of:\n\n    ";"\n    "<"\n    "@"\n    "abstract"\n    "boolean"\n    "byte"\n    "char"\n    "class"\n    "default"\n    "double"\n    "enum"\n    "final"\n    "float"\n    "int"\n    "interface"\n    "long"\n    "native"\n    "private"\n    "protected"\n    "public"\n    "short"\n    "static"\n    "strictfp"\n

**Comment by urialon** [comment]
Hi @BUCTwangkun ,
1. What did intend to do?
2. What command line exactly did you run?
3. What did you change compared to the original code?
4. Why did you preprocess Java-small, if it is already available preprocessed?

Best,
Uri

**Comment by BUCTwangkun** [comment]
Thanks for your reply~
1. I want to try to combine your model and mine, but our model's imputs are different.
2. sh preprocess.sh
3. I dont change the original code
4. Because of using multi-threads in your dataset, so the order of the dataset is different from mine. I want to preprocess java-small to keep same order

**Comment by urialon** [comment]
Which changes have you performed in `preprocess.sh`? 
Are you sure you are running this preprocessing on the raw .java files?

**Comment by BUCTwangkun** [comment]
I didnt change the preprocess.sh except the data path and num_thread(I set num_threads=1 in order to keep the same order)  and I am sure running this preprocessing on the raw .java files.
And I find there are errors just in running train set. The val and test dataset are right for me

**Comment by urialon** [comment]
I don't understand where this error is coming from, I'll try to check.
*BUT* - there is no guarantee on the order of examples, even if you are running with `num_threads=1`.
Even with `num_threads=1`, there are 6 processes (defined [here](https://github.com/tech-srl/code2seq/blob/master/JavaExtractor/extract.py#L66)), it's just that each of them runs with a single thread.

Even if you canceled that, and set it to run with 1 process having 1 thread - I am not sure that the order will be deterministic (for example, because I'm not sure that listing the files in a directory is deterministic).

I will still try to figure out what's wrong, but I recommend giving up on the order constraint or enforce it in some other way (e.g, assign each example a unique ID).

Please attach your terminal log (the stdout) when running preprocess.sh and the file `error_log.txt`. (delete `error_log.txt`, and run preprocess.sh to geta fresh `error_log.txt`).

**Comment by urialon** [comment]
Regarding the errors - you can ignore them. 
Some files in the training set simply don't parse. You can just ignore these errors and you will see that the training set still has almost 700k examples (`wc -l java-small.train.c2s`).

**Comment by BUCTwangkun** [comment]
ok, thanks you~
