### ISSUE TITLE
Clarifications on Combined Representation

### ISSUE THREAD

**Issue by hsellik** [tech-srl/code2seq#40]
Hi @urialon ,

Sorry for bothering again. I have some quick questions which I tried to make as clear as possible.

Looking at the Code Representation part we see that:

> <img width="851" alt="Screen Shot 2020-04-03 at 11 49 28" src="https://user-images.githubusercontent.com/16798824/78341973-3b1a8680-75a1-11ea-97cd-11f8c78b185e.png">

I assume that it is a similar fully connected layer as in Code2Vec model where the dense layer "combines" the terminals and paths to a certain dimension. The question I have.

1) Assuming that W_in are the weights for the dense layer, why is the dimension 2d_path +
2d_token) × d_hidden? Shouldn't it be something like new dimension d_hidden* x (1d_path + 2d_token)? 

*d_hidden being size for the combined representation which is the same as the decoder size - self.config.DECODER_SIZE

2) I am a bit confused with the notations. Namely, the terminals are marked as v_1 and v_l, but the path to be _encoded_ is also marked as v_1, ..., v_l . Does that mean that path that is to be encoded with LSTM also contains the terminals? This means that the terminals are also in the embedding matrix E^nodes?

3) Is there any difference between "encoding" and "embedding" here?

Right now I imagine model being something like this (without the attention):
[code2seq.pdf](https://github.com/tech-srl/code2seq/files/4427120/code2seq.pdf)

**Comment by urialon** [comment]
Hi @hsellik ,
No problem, feel free to ask questions.

Yes! this is similar to the dense layer of code2vec. 

1. The reason for 2d_path is that the path is encoded using a bidirectional LSTM, so we get two output vectors for the path, "forward" and "backwards". 

Now, for the question of whether the matrix is ((2d_path+2d_token) × d_hidden) or (d_hidden x (2d_path+2d_token)) - you are right. I think it should be as you say, (d_hidden x (2d_path+2d_token)) (i.e., d_hidden is first). 

Thank you for noticing.

2. Yeah, I agree, it is a bit confusing. v_1 and v_l are indeed the terminals, which come from the limited set of AST nodes. For example, such terminals are often: "NameExpr", "StringExpr", "IntegerExpr".  When we write that we "encode" the path, we mean that we use these symbols and the nonterminals between them. I.e., the path **does** contain the terminal.  When we call `encode_token`, we take the "value" of these terminals, which is a user-defined value. For example, by a "value" I refer to the number `3`, which can be the value of a terminal of type IntegerExpr. A possible value of a terminal of type NameExpr can be the value `mySqlConnection`.  

So E^{nodes} contain terminal types like NameExpr and IntExpr, along with nonterminal types like BlockStatement and ForeachStatement.
The other embedding matrix, E^{subtokens}, contains the subtokens "3", "my", "sql" and "connection".

Does that make sense?

3. Regarding "encoding" and "embedding": 

I usually refer to "embedding" as the vectors that are learned for each symbol, the learned vectors themselves; and I usually refer to "encoding" as something that requires some computation to represent. So, **encoding** a token can be performed by summing its subtoken **embeddings**.
 **encoding** a path can be performed by LSTM-ing its node type **embeddings**.

Does that make sense?

Regarding your chart - it looks accurate! But the best is to look at the code. If there is something you can't find in the code feel free to ask and I'll guide you.

**Comment by hsellik** [comment]
Thank you for the answers! They all make sense. 😄 :boom:

I do agree, looking at the code is the best source.

Got to finish off those Andrew Ng courses before tackling the full logic behind Code2Seq attention logic properly. 😅 On the bright side, Code2Vec model and the attention made a lot of sense!
