### ISSUE TITLE
preprocess  error

### ISSUE THREAD

**Issue by Henry199898** [tech-srl/code2seq#58]
when i run preprocess.sh, always got error_log.txt message: **dir: data/val/libgdx was not completed in time**, and my_dataset.val.raw.txt is empty.

I only  run one command "**${PYTHON} JavaExtractor/extract.py --dir ${VAL_DIR} --max_path_length 8 --max_path_width 2 --num_threads ${NUM_THREADS} --jar ${EXTRACTOR_JAR} > ${VAL_DATA_FILE} 2>> error_log.txt**" in preprocess.sh .

There are only over 200  *.java files in data/val  folder，I just want to try bash to deal with Java data.

![image](https://user-images.githubusercontent.com/62097361/86198336-fe533100-bb89-11ea-8cb1-c2304a218b7d.png).
and my java verison is 
> java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

My old computer is configured as follows：

> CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.3GHz 2.40 GHz
RAM: 8 GB
OS: win10

i can get some result by run `java -cp JavaExtractor/JPredict/target/JavaExtractor-0.0.1-SNAPSHOT.jar JavaExtractor.App --max_path_length 8 --max_path_width 2 --dir JavaExtractor/JPredict/src/main`
![image](https://user-images.githubusercontent.com/62097361/86198760-edef8600-bb8a-11ea-8082-bd1e7cf3a3b8.png)

I'm not sure if it's my configuration error or something else.
thank you very much indeed！

**Comment by urialon** [comment]
Hi @Henry199898 ,
I suspect that the reason is that you ran it under windows. 
I am guessing that input/output redirection doesn't work exactly the same in windows, and the code was written for linux.

A few users reported such problems under windows in the past, for example:
https://github.com/tech-srl/code2vec/issues/70

Can you try running it on a Linux VM?

Uri

**Comment by Henry199898** [comment]
It's really because of a system problem, I'm working properly on the linux server. Thank you for your solution

**Comment by Henry199898** [comment]
It's really because of a system problem, I'm working properly on the linux server. Thank you for your solution！！
