### ISSUE TITLE
Bleu=30.38 not 23.04

### ISSUE THREAD

**Issue by Moshiii** [tech-srl/code2seq#60]
Hi, Thanks for making your amazing work easy to reproduce first.

I am reproducing the model and I found the bleu score for java-large-test is 30.38. way better than the paper claimed 23.0
how do I reproduce the 23.04? am I doing something wrong here?

I used the common.sompute_bleu and configured the Perl script:
![image](https://user-images.githubusercontent.com/7553188/86502878-27381980-bd76-11ea-8401-2c8683f2d4c0.png)
but I get a better score:
![image](https://user-images.githubusercontent.com/7553188/86502910-69f9f180-bd76-11ea-8672-7cb570ac633c.png)

Any hints on this, please?

**Comment by urialon** [comment]
Hi @Moshiii ,
Thank you for your interest in code2seq!

The 23.04 BLEU score is for the much smaller C# dataset, not for Java.
In Java we measured only F1; in C# we measured only BLEU.

I hope it helps?
Uri

**Comment by Moshiii** [comment]
Hi Urialon,

Thanks for replying! this solves the myth! 

Just to share my bleu result on Java-small and Java-large:

![image](https://user-images.githubusercontent.com/7553188/86946280-286f9a80-c118-11ea-8c36-cad74276bc77.png)

the first bleu= 35.35 is from java-small dataset
the second bleu = 30.38 is from java-large dataset.
