### ISSUE TITLE
further training for the model

### ISSUE THREAD

**Issue by YawWQ** [tech-srl/code2seq#65]
Hello, my name is Yujing and I am an MSc student at the University of Leeds. I am very interested in this code2seq project and want to make some contributions to it. This trained model is in a "released" state, so what should I do if I want to continue to adjust this model? Thank you so much :D

**Comment by urialon** [comment]
Hi Yujing,
Thank you for your interest in code2seq.

Here is the trainable model, I will update the README as well:
```
https://code2seq.s3.amazonaws.com/model/java-large/java-large-trainable.tar.gz
```

**Comment by YawWQ** [comment]
> Hi Yujing,
> Thank you for your interest in code2seq.
> 
> Here is the trainable model, I will update the README as well:
> 
> ```
> https://code2seq.s3.amazonaws.com/model/java-large/java-large-trainable.tar.gz
> ```

It's really helpful. Hope I can train it successfully. Thank you so much!
