### ISSUE TITLE
Code for baselines reported in Table 1

### ISSUE THREAD

**Issue by JiyangZhang** [tech-srl/code2seq#68]
Hi, 

Thanks for your open-sourced code!
Just wonder do you have the code for the baselines such as BiLSTM?

Great thanks.

**Comment by urialon** [comment]
Hi @JiyangZhang ,
Thank you for your interest in code2seq!

The BiLSTM baseline was trained using [OpenNMT-py](https://opennmt.net/OpenNMT-py/).
It is an easy to use framework that lets you train sequence-to-sequence models using command lines only.

You can either [download our trained OpenNMT model](https://github.com/tech-srl/code2seq#using-the-trained-model) or train a model of your choice using [our data in the textual format](https://github.com/tech-srl/code2seq#using-the-trained-model).

Best,
Uri

**Comment by JiyangZhang** [comment]
Thank you! I will look at it
