### ISSUE TITLE
About the histogram file

### ISSUE THREAD

**Issue by chanrai** [tech-srl/code2seq#71]
When I preprocess with dataset, I can get some file like "my_dataset.histo.ori.c2s" and so on. 

What can these files be used for? For example, drawing a histogram? 

I looked inside the file but couldn't understand it.

Thanks and Best regards.

**Comment by urialon** [comment]
Hi @chanrai ,
These are internal files that contain histograms of tokens (and they are automatically deleted [later](https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L70)). Every line is a token and its counts in the training data.

You can see the [bash commands that created these files](https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L60), but why are you specifically interested in these temp files? are you looking for histograms?

**Comment by chanrai** [comment]
Thank you for the information.

>why are you specifically interested in these temp files? are you looking for histograms?

Yes, I want to express the learning transition of training data, test data, and evaluation data with a histogram, so I am thinking about how to do it.

For example, it is an image, such as shown in the [Fig. 5. Our model achieves significantly better results than the baselines and in shorter time] below of the paper.
[code2vec-popl19.pdf](https://urialon.cswp.cs.technion.ac.il/wp-content/uploads/sites/83/2018/12/code2vec-popl19.pdf)

Can you give me any advice?

Thanks and Best regards.

**Comment by urialon** [comment]
Sorry, I don't know...

**Comment by chanrai** [comment]
Thank you for your reply.
