### ISSUE TITLE
Error when using preprocess_csharp.sh

### ISSUE THREAD

**Issue by bhavyagera10** [tech-srl/code2seq#72]
Hello @urialon , I am working on preprocessing codeNN dataset via C
![issue2](https://user-images.githubusercontent.com/50918751/92261857-d2d92380-eef7-11ea-806b-34524f1fe379.png)

sharp extractor. When I open  preprocess_csharp.sh, I don't understand which are the paths to be sent for the extractor and am repeatedly getting errors. Can you please let me know which arguments to change , attaching the screenshot for your reference. Any help will be highly appreciated!

**Comment by bhavyagera10** [comment]
#69

**Comment by bhavyagera10** [comment]
Hi @urialon , I am training my CODENN dataset but getting these errors. I tried the hyper parameters you mentioned in #17 but still getting the errors. Can you please help me with it ?  

![error](https://user-images.githubusercontent.com/50918751/92278593-33298e80-ef13-11ea-8f55-bc6d65217397.png)

**Comment by urialon** [comment]
Hi @bhavyagera10 ,
We found the CodeNN dataset to be very noisy and I don't recommend using it. See additional discussion here: #17 

What errors are you getting? In your log I see prints like `hii` and `Model directory is mossing`, but I don't think that these come from our code.

**Comment by bhavyagera10** [comment]
Thank you for your prompt reply @urialon , I get it using TensorFlow 2.1 implementation here https://github.com/Kolkir/code2seq . Yes, these were debugging lines by me hii but Model directory is mossing is in the code. https://github.com/Kolkir/code2seq/blob/118f85250bbcc429a17e9b9cdcb73cb8eaae4767/modelrunner.py#L199  When I use train.sh, I get these errors in the modelrunner.py file https://github.com/Kolkir/code2seq/blob/master/modelrunner.py . I changed the config.py parameters according to #17 . I am facing the error that the "for loop "here https://github.com/Kolkir/code2seq/blob/118f85250bbcc429a17e9b9cdcb73cb8eaae4767/modelrunner.py#L113 does not run the required number of times that is num_epoch times which are 3000, as hii is printed only once. And hence my model is not training as you can see in the screenshots. I am attaching my train.sh, config.py, modelrunner.py and the errors. Please let me know, Thanks a lot :-) 
![config](https://user-images.githubusercontent.com/50918751/92280825-e8f6dc00-ef17-11ea-9e8f-c599e817d367.png)
![modelrunner](https://user-images.githubusercontent.com/50918751/92280853-f613cb00-ef17-11ea-9474-714295f4f056.png)
![debug](https://user-images.githubusercontent.com/50918751/92280868-00ce6000-ef18-11ea-9fe0-b79d8ca097c5.png)
![train2](https://user-images.githubusercontent.com/50918751/92280877-0af05e80-ef18-11ea-8269-6ef0cbf1fbf9.png)

**Comment by urialon** [comment]
Hi @bhavyagera10 ,
The repository https://github.com/Kolkir/code2seq is not mine.

**Comment by bhavyagera10** [comment]
Yes @urialon I understand , it was mentioned in the readme https://github.com/tech-srl/code2seq/blob/master/README.md . It is fine just in case you could help, maybe?

**Comment by urialon** [comment]
Sorry, I don't know what is the problem in a code that I didn't write.

**Comment by bhavyagera10** [comment]
Thanks @urialon , No problem!
