### ISSUE TITLE
Questions about MAX_CONTEXTS

### ISSUE THREAD

**Issue by lishi0927** [tech-srl/code2seq#73]
Hello, I have learned your codes and now I get a new question. I hope you can give me some help.

I find you use max_contexts to sample the (node, path, node) representation, If the codes are very long, the max_contexts = 200 still make sense?

I have this question because the code with 20 lines may generate over 1000 contexts, 200 will still be enough to represent this code?

Thank you.

**Comment by urialon** [comment]
Hi @lishi0927,

From my experience - more than 200 does not really improve the scores.
If your data is different - then there's no way to tell in advance, except
trying different values.
You can increase this number and see if it helps.

**Comment by lishi0927** [comment]
I got it.
Thank you for your reply.
