### ISSUE TITLE
Access to the original dataset

### ISSUE THREAD

**Issue by jonathansantilli** [tech-srl/code2seq#74]
Hello @urialon 

it is possible to have access to the original dataset (java source code) used to create the `java-large` model?

Cheers!

**Comment by urialon** [comment]
Hi @jonathansantilli ,
Sure - https://github.com/tech-srl/code2seq/#java

Uri

**Comment by jonathansantilli** [comment]
Upsss! thanks @urialon, I should have read that several times, and yet I had to ask 😄

**Comment by jonathansantilli** [comment]
Closing this since the question was answered.
