### ISSUE TITLE
vector extraction from the code

### ISSUE THREAD

**Issue by permitt** [tech-srl/code2seq#85]
I wanted to extract code vectors from the model. I found a way to get the vector for smaller methods, but I have a problem with the extract API you use. It timeouts for my longer methods, and it seems I have a lot of them in my dataset. The problem is with the POST request in extract.py.
Is there a way to extend the timeout or solve this problem in another way?

**Comment by urialon** [comment]
Hi @permitt ,
Thank you for your interest in code2seq.

The extract API simply wraps the [JavaExtractor](https://github.com/tech-srl/code2seq/tree/master/JavaExtractor) with a server that accepts POST requests. 
If your methods (and thus requests) are particularly long, you can use the JavaExtractor "offline" and let it run longer.

Best,
Uri

**Comment by permitt** [comment]
Yes, figured it out in the meanwhile :)
Thanks for your answer @urialon !
