### ISSUE TITLE
Obfuscated code2seq

### ISSUE THREAD

**Issue by AriYJ** [tech-srl/code2seq#92]
Inspired by https://github.com/basedrhys/obfuscated-code2vec, two other teammates and I trained code2seq on obfuscated data (using the obfuscator in the link earlier) and compared results. Just thought we'd post the link here in case anyone's interested:) https://github.com/AriYJ/Code2seqObfuscated

**Comment by urialon** [comment]
Hi @AriYJ ,
Thanks for sharing! Nice work!
