### ISSUE TITLE
Fine-tuning tips

### ISSUE THREAD

**Issue by DRMALEK** [tech-srl/code2seq#97]
Hi, 

I'm trying to fine-tune the code2seq model that is trained on the deepcom dataset on another more specific dataset (Android third-party libraries), so what are the general tips or guidelines for achieving such a thing.

Thanks in advance.

**Comment by urialon** [comment]
Hi @DRMALEK ,
I don't have any specific tips or guidelines, but this sounds like a very interesting direction.
Feel free to share the results or PDF.

Best,
Uri
