### ISSUE TITLE
Subtoken summation

### ISSUE THREAD

**Issue by 17385** [tech-srl/code2seq#98]
How do you achieve this by summing the subtoken vectors to represent the full token? Thanks

**Comment by urialon** [comment]
Hi @17385 ,
Thank you for your interest in code2seq!

I am not sure I understand the question.
Yes, we sum the subtoken vectors to represent the full token.
This is performed here:

https://github.com/tech-srl/code2seq/blob/428b1896a87e0c34af5a407c709c56047ec99a07/model.py#L531

Best,
Uri

**Comment by 17385** [comment]
Okay, I get it
